dist: bionic
sudo: required
language: cpp
compiler: gcc
env:
- CONFIG=Release PLATFORM=linux   BIT=64
- CONFIG=Release PLATFORM=linux   BIT=32
- CONFIG=Release PLATFORM=windows BIT=64
- CONFIG=Release PLATFORM=windows BIT=32
- CONFIG=Release PLATFORM=web BIT=64

- CONFIG=Debug PLATFORM=linux   BIT=64
- CONFIG=Debug PLATFORM=linux   BIT=32
- CONFIG=Debug PLATFORM=windows BIT=64
- CONFIG=Debug PLATFORM=windows BIT=32
- CONFIG=Debug PLATFORM=web BIT=64

install:
- sudo apt-get update
- ./scripts/fetch_dev_dependencies.sh
script:
- ./scripts/compile.sh
before_deploy:
- ./scripts/pack_artifacts.sh
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  prerelease: true
  api_key:
    secure: oD2FqISv2xZqbFTnJXRQ/q0ucdtiEdxQDtsvYzhLtU8vF+koM1WI6GdICGJGaGii2UDwFJwkkj81WMCFhZ+yJEsS59WBQdi8KS0vuPUtM73ndHU/CTV5/9PlXoMkWm1IF6gCiahXQ0wRioRHT/NqBOuxZcZOl7xbQWc7p74Jm+mwIXZd1ToRHArueM3Z/YakR+3SRut7sZBPisd2AXwIUULH+dFQXtFPRVyaTWiNLhMW2GIPzVPj9gLVa4qVHMnn0vevSAUym4qoL3MY8L52rIX2DlspbLgxnf9IyhVAIBIdzeQWOXlUJj03WnPvLtPed4F9aBOCdqlUQlkeUc/c24D/8l5MxHxzr8VHAUiEumdp3nx7G45/f1708kdJdKld3ESyXm92id/UXzYEmNhF89n4EEZrL6NEVkq4EsoTFmIjZL85v5GsVR50qaRQkmTzlXhkr3Gh6KBQepTZHKYRTG/ThGDosyDIRW/y07A+04bA6iJbpHHaOry8+pKerHRHRp6QWpmvnd3YMZn3xRrSW7iBeq82UiyC4iagMCYFWJ41gYxgm4We4IiIe3TZ/O6L8WCQSCVw1assUHbU0ELJOBC05nRnXtYxIIsZAPt6pHTII2Cixo//AK502QKw5W3wQnXRtXByrBEVAA94UwuLsyianBxXhjFoSiQQmvltkLc=
  file: ld-46-game*
  on:
    tags: true
    condition: $CONFIG = Release
    branch: master
    repo: AgoutiGames/ld-46-game
